const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('../app/src/main/assets/realschule/core.js');
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
test('safe exact parser: fractions, decimal comma, negatives, precedence and parentheses',()=>{for(const [s,n,d] of [['2/4',1,2],['-0,25',-1,4],['2*(3+4)',14,1],['-2^2',-4,1],['(-2)^2',4,1],['1/3+1/6',1,2],['0/7',0,1]])assert.deepEqual(M.constant(s),M.Q(n,d));assert.equal(M.equation('2(x+3)=4x-2').root.n,4);});
test('invalid and hostile input is rejected without execution',()=>{for(const s of ['','1/0','1/(2-2)','process.exit()','alert(1)','1e309','x/x','2^99','('.repeat(30)+'1'+')'.repeat(30),'1++','9007199254740992'])assert.throws(()=>M.constant(s),s);});
test('equivalent equation transformations, fractions and alternate routes accepted',()=>{const t={type:'equationSteps',original:'3x+5=20',answer:M.Q(5)};assert.equal(M.validate(t,'6x=30').status,'step');assert.equal(M.validate(t,'x=5',['6x=30']).status,'correct');assert.equal(M.validate(t,'x=10/2',['x+1=6']).status,'correct');assert.equal(M.validate(t,'5=x',['3x=15']).status,'correct');assert.equal(M.validate(t,'x=5',['1x=5']).status,'correct');assert.equal(M.validate(t,'x=5').status,'incomplete');assert.equal(M.validate(t,'3x=20').status,'wrong');assert.equal(M.validate(t,'3x+5=20').status,'invalid');assert.equal(M.validate(t,'3x=15',['3x=15']).status,'invalid');assert.equal(M.validate(t,'x*x=25').status,'invalid');});
test('fraction steps: reduce separately, accept pre-cancellation, require a real intermediate',()=>{const t={type:'fractionSteps',original:'2/3*3/4',answer:M.Q(1,2)};assert.equal(M.validate(t,'1/2').status,'incomplete');assert.equal(M.validate(t,'6/12').status,'step');assert.equal(M.validate(t,'1/2',['6/12']).status,'correct');assert.equal(M.validate(t,'1*1/2').status,'step');assert.equal(M.validate(t,'1/2',['1*1/2']).status,'correct');assert.equal(M.validate(t,'2/4',['6/12']).status,'step');assert.equal(M.validate(t,'6/7').status,'wrong');assert.equal(M.validate(t,'1/0').status,'invalid');});
test('short answers: equivalent values, units, rounding, zero',()=>{const t={type:'short',answer:M.Q(1,2),unit:'cm²',tolerance:0};assert.equal(M.validate(t,'0,5 cm2').status,'correct');assert.equal(M.validate(t,'2/4 cm²').status,'correct');assert.equal(M.validate(t,'0,5 cm').status,'invalid');assert.equal(M.validate(t,'0.499').status,'wrong');assert.equal(M.validate({...t,answer:M.Q(0)},'0').status,'correct');assert.equal(M.validate({...t,tolerance:0.005000001},'0,504').status,'correct');assert.equal(M.validate({...t,tolerance:0.005000001},'0,506').status,'wrong');});
test('all curriculum rows have working variable generators and valid solutions (5,300 cases)',()=>{let count=0;for(let g=5;g<=10;g++)for(const group of ['I','II/III'])for(const topic of M.topics(g,group))for(const difficulty of ['easy','medium','hard','mixed']){const variants=new Set();for(let seed=1;seed<=25;seed++){const t=M.generate(topic.id,g,difficulty,rng(seed*1234567));assert(Number.isSafeInteger(t.answer.n));assert(t.answer.d>0);variants.add(t.prompt);if(t.type==='equationSteps'){assert.equal(M.eq(M.equation(t.original).root,t.answer),true);assert.equal(M.validate(t,t.steps[0]).status,'step');assert.equal(M.validate(t,t.steps[1],[t.steps[0]]).status,'correct');}else if(t.type==='fractionSteps'){assert.equal(M.validate(t,t.steps[0]).status,'step');assert.equal(M.validate(t,t.steps[1],[t.steps[0]]).status,'correct');}else assert.equal(M.validate(t,M.str(t.answer)).status,'correct');count++;}assert(variants.size>5,topic.id);assert(topic.source.startsWith('https://www.lehrplanplus.bayern.de/'));}console.log('Generated and validated',count,'tasks');});
test('Wahlpflichtfächergruppen and basics are not mixed into grade difficulty',()=>{assert(!M.topics(5).some(t=>t.id==='fractions'));assert(M.topics(6).some(t=>t.id==='equations'));assert(M.topics(9,'I').some(t=>t.id==='quadratic'));assert(!M.topics(9,'II/III').some(t=>t.id==='quadratic'));assert(!M.topics(10,'I').some(t=>t.id==='cylinder'));assert(M.topics(10,'II/III').some(t=>t.id==='cylinder'));assert.throws(()=>M.generate('placeholder',5));});
