const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('../app/src/main/assets/realschule/core.js');
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
test('safe exact parser: fractions, decimal comma, negatives, precedence and parentheses',()=>{for(const [s,n,d] of [['2/4',1,2],['-0,25',-1,4],['2*(3+4)',14,1],['-2^2',-4,1],['(-2)^2',4,1],['1/3+1/6',1,2],['0/7',0,1]])assert.deepEqual(M.constant(s),M.Q(n,d));assert.equal(M.equation('2(x+3)=4x-2').root.n,4);});
test('invalid and hostile input is rejected without execution',()=>{for(const s of ['','1/0','1/(2-2)','process.exit()','alert(1)','1e309','x/x','2^99','('.repeat(30)+'1'+')'.repeat(30),'1++','9007199254740992'])assert.throws(()=>M.constant(s),s);});
test('equivalent equation transformations, fractions and alternate routes accepted',()=>{const t={type:'equationSteps',original:'3x+5=20',answer:M.Q(5)};assert.equal(M.validate(t,'6x=30').status,'step');assert.equal(M.validate(t,'x=5',['6x=30']).status,'correct');assert.equal(M.validate(t,'x=10/2',['x+1=6']).status,'correct');assert.equal(M.validate(t,'5=x',['3x=15']).status,'correct');assert.equal(M.validate(t,'x=5',['1x=5']).status,'correct');assert.equal(M.validate(t,'x=5').status,'incomplete');assert.equal(M.validate(t,'3x=20').status,'wrong');assert.equal(M.validate(t,'3x+5=20').status,'invalid');assert.equal(M.validate(t,'3x=15',['3x=15']).status,'invalid');assert.equal(M.validate(t,'x*x=25').status,'invalid');});
test('fraction steps: reduce separately, accept pre-cancellation, require a real intermediate',()=>{const t={type:'fractionSteps',original:'2/3*3/4',answer:M.Q(1,2)};assert.equal(M.validate(t,'1/2').status,'incomplete');assert.equal(M.validate(t,'6/12').status,'step');assert.equal(M.validate(t,'1/2',['6/12']).status,'correct');assert.equal(M.validate(t,'1*1/2').status,'step');assert.equal(M.validate(t,'1/2',['1*1/2']).status,'correct');assert.equal(M.validate(t,'2/4',['6/12']).status,'step');assert.equal(M.validate(t,'6/7').status,'wrong');assert.equal(M.validate(t,'1/0').status,'invalid');});
test('short answers: equivalent values, units, rounding, zero',()=>{const t={type:'short',answer:M.Q(1,2),unit:'cm²',tolerance:0};assert.equal(M.validate(t,'0,5 cm2').status,'correct');assert.equal(M.validate(t,'2/4 cm²').status,'correct');assert.equal(M.validate(t,'0,5 cm').status,'invalid');assert.equal(M.validate(t,'0.499').status,'wrong');assert.equal(M.validate({...t,answer:M.Q(0)},'0').status,'correct');assert.equal(M.validate({...t,tolerance:0.005000001},'0,504').status,'correct');assert.equal(M.validate({...t,tolerance:0.005000001},'0,506').status,'wrong');});
test('all curriculum rows have working variable generators and valid solutions (12,700 cases)',()=>{let count=0;for(let g=5;g<=10;g++)for(const group of ['I','II/III'])for(const topic of M.topics(g,group))for(const difficulty of ['easy','medium','hard','mixed']){const variants=new Set();for(let seed=1;seed<=25;seed++){const t=M.generate(topic.id,g,difficulty,rng(seed*1234567));assert(Number.isSafeInteger(t.answer.n));assert(t.answer.d>0);variants.add(t.prompt);if(t.type==='quadraticSteps'){assert.equal(M.validate(t,t.steps[0]).status,'step');assert.equal(M.validate(t,t.steps[1],[t.steps[0]]).status,'correct');}else if(t.type==='rationalSteps'){assert.equal(M.validate(t,t.steps[0]).status,'step');assert.equal(M.validate(t,t.steps[1],[t.steps[0]]).status,'step');assert.equal(M.validate(t,t.steps[2],t.steps.slice(0,2)).status,'correct');}else if(t.type==='systemSteps'){assert.deepEqual(M.solveSystem(t.originals),t.solution);assert.equal(M.validate(t,t.steps[0]).status,'step');assert.equal(M.validate(t,t.steps[1],[t.steps[0]]).status,'step');assert.equal(M.validate(t,t.steps[2],t.steps.slice(0,2)).status,'correct');}else if(t.type==='equationSteps'){assert.equal(M.eq(M.equation(t.original).root,t.answer),true);assert.equal(M.validate(t,t.steps[0]).status,'step');assert.equal(M.validate(t,t.steps[1],[t.steps[0]]).status,'correct');}else if(t.type==='fractionSteps'){assert.equal(M.validate(t,t.steps[0]).status,'step');assert.equal(M.validate(t,t.steps[1],[t.steps[0]]).status,'correct');}else assert.equal(M.validate(t,M.str(t.answer)).status,'correct');count++;}assert(variants.size>5,topic.id);assert(topic.source.startsWith('https://www.lehrplanplus.bayern.de/'));}console.log('Generated and validated',count,'tasks');});
test('Wahlpflichtfächergruppen and basics are not mixed into grade difficulty',()=>{assert(!M.topics(5).some(t=>t.id==='fractions'));assert(M.topics(6).some(t=>t.id==='equations'));assert(M.topics(9,'I').some(t=>t.id==='quadratic'));assert(!M.topics(9,'II/III').some(t=>t.id==='quadratic'));assert(!M.topics(10,'I').some(t=>t.id==='cylinder'));assert(M.topics(10,'II/III').some(t=>t.id==='cylinder'));assert.throws(()=>M.generate('placeholder',5));});
test('mixed numbers retain their value, sign and boundaries',()=>{
 for(const [s,n,d] of [['2 1/3',7,3],['-2 1/3',-7,3],['2 1/3 + 1 1/6',7,2],['(-1 1/2)*2',-3,1],['1 0/3',1,1],['(2/3):(4/5)',5,6]])assert.deepEqual(M.constant(s),M.Q(n,d));
 for(const s of ['1 2','2 4/3','2 1/0','1 2/2','2 1/-3','99999999999999999999 1/2'])assert.throws(()=>M.constant(s),s);
 const t={type:'fractionSteps',original:'1/3+1/6',answer:M.Q(1,2)};assert.equal(M.validate(t,'(1/3 + 1/6)').status,'invalid');assert.equal(M.validate(t,'(2+1)/6').status,'step');assert.equal(M.validate(t,'1/2',['(2+1)/6']).status,'correct');
 const mixed={type:'fractionSteps',original:'1 1/3 + 1',answer:M.Q(7,3)};assert.equal(M.validate(mixed,'2 1/3',['4/3+1']).status,'step');assert.equal(M.validate(mixed,'7/3',['4/3+1']).status,'correct');
});
test('fraction operation examples allow alternate denominators, reciprocal and conversion routes',()=>{
 const add={type:'fractionSteps',original:'1/3+1/4',answer:M.Q(7,12)};assert.equal(M.validate(add,'8/24+6/24').status,'step');assert.equal(M.validate(add,'14/24',['8/24+6/24']).status,'step');assert.equal(M.validate(add,'7/12',['8/24+6/24','14/24']).status,'correct');assert.equal(M.validate(add,'7/7').status,'wrong');
 const sub={type:'fractionSteps',original:'1/2-3/4',answer:M.Q(-1,4)};assert.equal(M.validate(sub,'(2-3)/4').status,'step');assert.equal(M.validate(sub,'-1/4',['(2-3)/4']).status,'correct');assert.equal(M.validate(sub,'− 1/4',['(2-3)/4']).status,'correct');
 const zero={type:'fractionSteps',original:'1/2-2/4',answer:M.Q(0)};assert.equal(M.validate(zero,'(2-2)/4').status,'step');assert.equal(M.validate(zero,'0',['(2-2)/4']).status,'correct');
 const divide={type:'fractionSteps',original:'(2/3)/(4/5)',answer:M.Q(5,6)};assert.equal(M.validate(divide,'(2/3)*(5/4)').status,'step');assert.equal(M.validate(divide,'5/6',['(2/3)*(5/4)']).status,'correct');assert.equal(M.validate(divide,'(2/3)*(4/5)').status,'wrong');
});
test('two-variable affine parser: exact fractions, nesting, signs and rejection of nonlinear input',()=>{
 assert.deepEqual(M.parseLinear2('2(x+y)-y/2+0,5'),[M.Q(1,2),M.Q(2),M.Q(3,2)]);
 for(const s of ['x*y','x²','1/x','1/(y-y)','Math.random()','x + z','x=1','('.repeat(30)+'x'+')'.repeat(30),'x^99'])assert.throws(()=>M.parseLinear2(s),s);
 assert.throws(()=>M.solveSystem(['x+y=3','2x+2y=6']));assert.throws(()=>M.solveSystem(['x+y=3','2x+2y=7']));assert.throws(()=>M.solveSystem(['0=0','x=1']));
 assert.deepEqual(M.solveSystem(['x+y=0','x-y=0']),{x:M.Q(0),y:M.Q(0)});
});
test('systems support elimination, substitution and both answer orders, but require evidence and both variables',()=>{
 const t={type:'systemSteps',originals:['2x+y=7','x-y=2'],solution:{x:M.Q(3),y:M.Q(1)}};
 assert.equal(M.validate(t,'x=3; y=1').status,'incomplete');assert.equal(M.validate(t,'x=3').status,'incomplete');assert.equal(M.validate(t,'2x+y=7').status,'invalid');
 assert.equal(M.validate(t,'3x=9').status,'step');assert.equal(M.validate(t,'x=3',['3x=9']).status,'step');assert.equal(M.validate(t,'y=1',['3x=9','x=3']).status,'correct');
 assert.equal(M.validate(t,'y=1; x=6/2',['3x=9']).status,'correct');assert.equal(M.validate(t,'2x+(x-2)=7').status,'step');assert.equal(M.validate(t,'x=3; y=1',['2x+(x-2)=7']).status,'correct');
 assert.equal(M.validate(t,'2(2x+y)=14').status,'step');assert.equal(M.validate(t,'x=3',['2(2x+y)=14']).status,'incomplete');
 assert.equal(M.validate(t,'3x=8').status,'wrong');assert.equal(M.validate(t,'y=2',['3x=9']).status,'wrong');assert.equal(M.validate(t,'x=3; y=2',['3x=9']).status,'wrong');assert.equal(M.validate(t,'x=3; x=3',['3x=9']).status,'invalid');assert.equal(M.validate(t,'x=3;',['3x=9']).status,'invalid');assert.equal(M.validate(t,'0=0').status,'invalid');
 const fractions={type:'systemSteps',originals:['x+y=1/6','2x-y=-7/6'],solution:{x:M.Q(-1,3),y:M.Q(1,2)}};assert.equal(M.validate(fractions,'3x=-1').status,'step');assert.equal(M.validate(fractions,'x=-2/6; y=0,5',['3x=-1']).status,'correct');
});
test('new curriculum topics are offered only in the proper grade, with existing multiplication retained',()=>{
 for(const id of ['fractions','fractionAdd','fractionSubtract','fractionDivide','mixedFractions'])assert(M.topics(6).some(t=>t.id===id));assert(!M.topics(5).some(t=>t.id==='fractionAdd'));
 for(const group of ['I','II/III']){assert(M.topics(9,group).some(t=>t.id==='systems'));assert(!M.topics(8,group).some(t=>t.id==='systems'));}
});

test('new arithmetic respects parentheses and grade placement',()=>{assert(M.topics(6).some(t=>t.id==='fractionChain'));assert(M.topics(7).some(t=>t.id==='termValue'));assert(!M.topics(5).some(t=>t.id==='fractionChain'));for(const difficulty of ['easy','medium','hard']){const t=M.generate('termValue',7,difficulty,rng(7654321));const x=t.prompt.match(/x = (-?\d+)/)[1],expression=t.prompt.match(/rs-equation">([^<]+)/)[1].replace(/x/g,'('+x+')');assert(M.eq(M.constant(expression),t.answer));const chain=M.generate('fractionChain',6,difficulty,rng(234567));assert(M.eq(M.constant(chain.original),chain.answer));assert.equal(M.validate(chain,chain.steps[1]).status,'incomplete');}});

test('phase 3: graphs and zeros match independently evaluated functions and grade groups',()=>{
 for(const difficulty of ['easy','medium','hard'])for(let seed=1;seed<=100;seed++){
   const graph=M.generate('linearGraph',8,difficulty,rng(seed));const {slope,intercept,x,reading}=graph.graph;
   const expected=reading==='slope'?slope:reading==='intercept'?M.Q(intercept):M.add(M.mul(slope,M.Q(x)),M.Q(intercept));assert(M.eq(graph.answer,expected));assert(Math.abs(slope.n/slope.d*x+intercept)<=6);assert(graph.prompt.includes('<svg'));assert(!graph.prompt.includes('http'));assert.equal(M.validate(graph,M.str(M.add(expected,M.Q(1)))).status,'wrong');
   const linear=M.generate('linearZero',8,difficulty,rng(seed));assert(M.eq(M.add(linear.coefficients[0],M.mul(linear.coefficients[1],linear.answer)),M.Q(0)));
   const quad=M.generate('quadraticZero',9,difficulty,rng(seed));assert(quad.roots[0].n/quad.roots[0].d<quad.answer.n/quad.answer.d);for(const r of quad.roots)assert(M.eq(M.add(M.add(quad.coefficients[0],M.mul(quad.coefficients[1],r)),M.mul(quad.coefficients[2],M.mul(r,r))),M.Q(0)));assert.equal(M.validate(quad,M.str(quad.roots[0])).status,'wrong');
 }
 assert(M.topics(9,'I').some(t=>t.id==='quadraticZero'));assert(!M.topics(9,'II/III').some(t=>t.id==='quadraticZero'));assert(M.topics(10,'II/III').some(t=>t.id==='quadraticZero'));assert(!M.topics(10,'I').some(t=>t.id==='quadraticZero'));
});

test('rational equations enforce excluded value, cleared step and final assignment',()=>{
 const t=M.generate('rationalEquation',8,'hard',rng(12));assert.equal(M.validate(t,t.steps[2]).status,'incomplete');assert.equal(M.validate(t,'D: x != '+M.str(M.add(t.excluded,M.Q(1)))).status,'wrong');assert.equal(M.validate(t,t.steps[2],[t.steps[0]]).status,'incomplete');assert.equal(M.validate(t,'x = '+M.str(t.excluded),t.steps.slice(0,2)).status,'wrong');assert(M.eq(M.div(t.numerator,M.add(t.answer,M.Q(-t.excluded.n,t.excluded.d))),t.factor));
});
test('quadratic equations require both distinct roots and a real transformation',()=>{
 const t=M.generate('quadraticEquation',9,'hard',rng(4)),first='x = '+M.str(t.roots[0]),second='x = '+M.str(t.roots[1]);assert.equal(M.validate(t,first+'; '+second).status,'incomplete');assert.equal(M.validate(t,t.original).status,'invalid');assert.equal(M.validate(t,'x^2 = 999').status,'wrong');assert.equal(M.validate(t,first,[t.steps[0]]).status,'step');assert.equal(M.validate(t,first+'; '+first,[t.steps[0]]).status,'step');assert.equal(M.validate(t,second,[t.steps[0],first]).status,'correct');assert.equal(M.validate(t,second+'; '+first,[t.steps[0]]).status,'correct');assert.equal(M.validate(t,'x = 999',[t.steps[0]]).status,'wrong');
});
test('new word problems and advanced generators match independent reference calculations',()=>{
 const num=q=>q.n/q.d;
 for(let seed=1;seed<=100;seed++)for(const difficulty of ['easy','medium','hard']){
 for(const [id,grade] of [['divisionRemainder',5],['percentBase',6],['percentRate',6],['fractionPercent',6],['inverseRatio',7],['median',7],['mode',7],['linearSlope',8],['lineIntersection',8],['trigRight',9],['noReplacement',9],['logarithm',10],['decay',10],['quadraticCount',9]]){
 const t=M.generate(id,grade,difficulty,rng(seed)),f=t.facts;let expected;
 switch(id){case 'divisionRemainder':expected=f.value%f.divisor;break;case 'percentBase':expected=f.value*100/f.pct;break;case 'percentRate':expected=f.value/f.base*100;break;case 'fractionPercent':expected=num(f.fraction)*100;break;case 'inverseRatio':expected=f.workers*f.hours/f.newWorkers;break;case 'median':{const a=[...f.values].sort((a,b)=>a-b);expected=a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;break;}case 'mode':{const counts={};for(const v of f.values)counts[v]=(counts[v]||0)+1;expected=Number(Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0]);break;}case 'linearSlope':expected=(f.y2-f.y1)/(f.x2-f.x1);break;case 'lineIntersection':expected=(f.d-f.b)/(f.a-f.c);break;case 'trigRight':expected=Number((f.hyp*Math.sin(f.angle*Math.PI/180)).toFixed(2));break;case 'noReplacement':expected=f.red/(f.red+f.blue)*(f.red-1)/(f.red+f.blue-1);break;case 'logarithm':expected=Math.log(f.value)/Math.log(f.base);break;case 'decay':expected=Number((f.start*Math.pow(1-f.pct/100,f.years)).toFixed(2));break;case 'quadraticCount':expected=f.c>0?0:f.c===0?1:2;break;}
 assert(Math.abs(num(t.answer)-expected)<1e-9,id);
 }
 const rational=M.generate('rationalEquation',8,difficulty,rng(seed));assert(!M.eq(rational.answer,rational.excluded));assert(M.eq(M.div(rational.numerator,M.add(rational.answer,M.Q(-rational.excluded.n,rational.excluded.d))),rational.factor));
 const quad=M.generate('quadraticEquation',9,difficulty,rng(seed));for(const r of quad.roots)assert(M.eq(M.add(M.add(quad.coefficients[0],M.mul(quad.coefficients[1],r)),M.mul(quad.coefficients[2],M.mul(r,r))),M.Q(0)));
 }
});
