// Run with Playwright installed and CHROMIUM_PATH set if needed.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{
const version=fs.readFileSync(path.resolve(__dirname,'../version.properties'),'utf8').match(/VERSION_NAME=(\d+)/)[1];
const assets=path.resolve(__dirname,'../app/src/main/assets'),browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];
page.setDefaultTimeout(10000);page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});await context.route('**/*',r=>{const name=new URL(r.request().url()).pathname.replace('/RechenGuruLGI_AndroidAPK/','')||'index.html',file=path.join(assets,name);if(fs.existsSync(file)&&fs.statSync(file).isFile())return r.fulfill({body:fs.readFileSync(file),contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':name.endsWith('.js')?'application/javascript':undefined});return r.abort();});
await page.addInitScript(v=>{window.AndroidInterface={getAppVersionName:()=>v,openExternal:()=>true,shareLink:()=>true};},version);
await page.goto('https://parip69.github.io/RechenGuruLGI_AndroidAPK/?v='+version);await page.waitForTimeout(1200);console.log('loaded');
const gs=await page.evaluate(()=>{const input=document.querySelector('#zeilenAufgaben input:not([disabled])');if(input)input.value='7';return {task:Array.from(document.querySelectorAll('#zeilenAufgaben [data-task]')).map(e=>e.dataset.task),values:Array.from(document.querySelectorAll('#zeilenAufgaben input')).map(e=>e.value),keys:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('RechenGuruLGI_')).map(k=>[k,localStorage.getItem(k)]))};});
await page.locator('#realschuleTab').click();assert(await page.locator('#realschulePanel').isVisible());assert(!(await page.locator('#grundschulePanel').isVisible()));
console.log('rs tab');await page.locator('#rsAll').uncheck();for(const c of await page.locator('[data-topic]').all())await c.uncheck();await page.locator('[data-topic="6:equations"]').check();await page.locator('#rsStart').click();console.log('started');
let t=await page.evaluate(()=>{const c=RealschuleUI.getState().session.current;let seed=c.seed;return MatheRealschule.generate(c.id,c.grade,c.difficulty,()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;});});
await page.locator('#rsAnswer').fill(t.steps[1]);await page.locator('#rsCheck').click();assert((await page.locator('#rsFeedback').innerText()).includes('zuerst'));assert.equal(await page.evaluate(()=>RealschuleUI.getState().session.count),0);
await page.locator('#rsAnswer').fill('x=999');await page.locator('#rsCheck').click();assert.equal(await page.evaluate(()=>RealschuleUI.getState().session.wrong),1);
await page.locator('#rsAnswer').fill(t.steps[0]);await page.locator('#rsCheck').click();await page.locator('#rsAnswer').fill(t.steps[1]);await page.locator('#rsCheck').click();assert.equal(await page.evaluate(()=>RealschuleUI.getState().session.correct),1);
const snapshot=await page.evaluate(()=>JSON.stringify(RealschuleUI.getState()));await page.locator('#grundschuleTab').click();assert.deepEqual(await page.evaluate(()=>({task:Array.from(document.querySelectorAll('#zeilenAufgaben [data-task]')).map(e=>e.dataset.task),values:Array.from(document.querySelectorAll('#zeilenAufgaben input')).map(e=>e.value),keys:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('RechenGuruLGI_')).map(k=>[k,localStorage.getItem(k)]))})),gs);
await page.locator('#realschuleTab').click();assert.equal(await page.evaluate(()=>JSON.stringify(RealschuleUI.getState())),snapshot);
await page.reload();await page.waitForTimeout(1000);assert(await page.locator('#realschulePanel').isVisible());assert.equal(await page.evaluate(()=>RealschuleUI.getState().session.correct),1);
await page.locator('#rsNext').click();await page.locator('#rsHint').click();assert((await page.locator('#rsFeedback').innerText()).length>10);await page.locator('#rsSolution').click();assert.equal(await page.evaluate(()=>RealschuleUI.getState().session.assisted),1);
page.on('dialog',d=>d.accept());await page.locator('.rs-progress > summary').click();await page.locator('#rsReview').click();assert.equal(await page.evaluate(()=>RealschuleUI.getState().session.review),true);assert.equal(await page.evaluate(()=>RealschuleUI.getState().session.current.id),'equations');
const reviewPrompt=await page.locator('.rs-prompt').innerHTML();assert.notEqual(reviewPrompt,t.prompt);
await page.locator('.rs-settings > summary').click();await page.locator('#rsGrade').selectOption('9');assert.equal(await page.locator('[data-topic="9:quadratic"]').count(),1);await page.locator('#rsGroup').selectOption('II/III');assert.equal(await page.locator('[data-topic="9:quadratic"]').count(),0);await page.locator('#rsGrade').selectOption('10');assert.equal(await page.locator('[data-topic="10:cylinder"]').count(),1);await page.locator('#rsGroup').selectOption('I');assert.equal(await page.locator('[data-topic="10:cylinder"]').count(),0);await page.locator('#rsBasics').check();assert.equal(await page.locator('[data-topic="6:fractions"]').count(),1);assert.equal(await page.locator('.rs-prompt').innerHTML(),reviewPrompt);await page.locator('.rs-settings > summary').click();

for(const width of [320,390,768]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
await page.screenshot({path:'/workspace/.cloud-tools/artifacts/realschule'+version+'.png',fullPage:true});
const bundled=await page.evaluate(async()=>bundleRealschuleAssets(await getBundledIndexHtmlText()));assert(!bundled.includes('<script src="realschule/'));assert(!bundled.includes('<link rel="stylesheet" href="realschule/'));
const offline=await context.newPage();offline.on('pageerror',e=>errors.push(e.message));await offline.route('**/portable.html',r=>r.fulfill({contentType:'text/html',body:bundled}));await context.setOffline(true);await offline.goto('https://parip69.github.io/RechenGuruLGI_AndroidAPK/portable.html');await context.setOffline(false);assert.equal(await offline.locator('[data-school-tab]').count(),2);assert(await offline.evaluate(()=>typeof MatheRealschule.generate==='function'));
// A running Grundschule timer is paused while Realschule is visible, including on reload.
await page.evaluate(()=>{window.__schoolSection='grundschule';window._roundTimerDeadline=Date.now()+1000;window._roundTimerTimeout=setTimeout(()=>{window.timerExpired=true;},1000);RealschuleUI.switchSection('realschule');});await page.waitForTimeout(1200);assert.equal(await page.evaluate(()=>!!window.timerExpired),false);await page.evaluate(()=>RealschuleUI.switchSection('grundschule'));assert(await page.evaluate(()=>!!window._roundTimerTimeout));
await page.evaluate(()=>RealschuleUI.switchSection('realschule'));
const repeat=await page.evaluate(()=>{const c=RealschuleUI.getState().session.current;let seed=c.seed;return MatheRealschule.generate(c.id,c.grade,c.difficulty,()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;});});
await page.locator('#rsAnswer').fill(repeat.steps[0]);await page.locator('#rsCheck').click();await page.locator('#rsAnswer').fill(repeat.steps[1]);await page.locator('#rsCheck').click();await page.locator('#rsNext').click();assert((await page.locator('#rsSession').innerText()).includes('Runde abgeschlossen'));assert.equal(await page.evaluate(()=>RealschuleUI.getState().errors.length),0);
assert.deepEqual(errors,[]);console.log('PASS: tabs, unchanged Grundschule data/task, multi-step equation, progress, reload, solution, mobile widths, portable HTML, paused timer');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
